# Available options listed at;
# https://docs.helix-editor.com/configuration.html

theme = "onedark"

[editor]
bufferline = "always"
color-modes = true
completion-replace = true
cursorline = true
line-number = "relative" # absolute is default
text-width = 80
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-indent-retain = 0
max-wrap = 25
wrap-at-text-width = true
wrap-indicator = ""  # Use "" to hide indicator

[keys.normal] # Key mapping in normal mode
"ins" = "insert_mode"
"del" = "delete_selection"
"C-home" = "goto_file_start" # Ctrl-home = go to top of file
"C-end" = "goto_last_line" # Ctrl-end = go to end of file

[keys.normal."\\"]
# Tapping '\' will bring up my list of custom actions
# View the target files at '~/bin/helix' for more information on each
"c" = ":config-open"
"f" = ":run-shell-command /usr/bin/pandoc -t markdown-simple_tables"
"i" = ":insert-output ~/bin/helix/snippet-single-image"
"m" = ":insert-output ~/bin/helix/snippet-multi-images"
"p" = ":run-shell-command ~/bin/helix/hx-md-to-pdf.sh" # Print to pdf
"r" = ":reload" # Reload current file and discard changes
"s" = ":run-shell-command ~/bin/helix/hx-spellcheck.sh" # Spellcheck
