# Options are listed at https://docs.helix-editor.com/configuration.html

theme = "onedark"

[editor]
bufferline = "always"
color-modes = true
completion-replace = true
cursorline = true
line-number = "relative" # absolute is default
text-width = 80
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-indent-retain = 0
max-wrap = 25
wrap-at-text-width = true
wrap-indicator = ""  # Use "" to hide indicator

[keys.normal]
"ins" = "insert_mode" # Until I get used to using "i"!
