# Guidance
# --------
#
# Helix Language Support
# https://docs.helix-editor.com/lang-support.html

# Installing Default Language Servers
# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

# Languages
# ---------
#
# Bash
# Install with the command:
# npm i -g bash-language-server

# CSS
# Install with the command:
# npm i -g vscode-langservers-extracted

# Dot for Graphviz
# Install with the command:
# npm i -g dot-language-server

# HTML
# Install with the command:
# npm i -g vscode-langservers-extracted

# JSON
# Install with the command:
# npm i -g vscode-langservers-extracted
# Configuration:
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }

# Marksman LSP for Markdown
# Installation options can be found at: https://github.com/artempyanykh/marksman/blob/main/docs/install.md
# Marksman requires no configuration.

# YAML
# Install with the command
# npm i -g yaml-language-server@next
# Configuration:
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
